### ISSUE TITLE
vanilla start fails with node 17

### ISSUE THREAD

**Issue by meunierfrederic** [sinequa/sba-angular#57]
The "Getting started" falis with current version of node (17.1.0) when starting vanilla-search (see below). 
Maybe you should add a .nvmrc file to the project and specify which version of node is embedded in the Sinequa distribution.

Thanks

Fred

```
npm run ng serve vanilla-search -- --ssl=true --proxyConfig=./projects/vanilla-search/src/proxy.conf.json

/ Generating browser application bundles (phase: building)...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\lib\util\createHash.js:46:50)
    at RawSource.updateHash (C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\node_modules\webpack-sources\lib\RawSource.js:70:8)
    at NormalModule._initBuildHash (C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\lib\NormalModule.js:880:17)
    at handleParseResult (C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\lib\NormalModule.js:946:10)
    at C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\lib\NormalModule.js:1040:4
    at processResult (C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\lib\NormalModule.js:755:11)
    at C:\sinequa\data\sba\sinequa-sba-angular\node_modules\webpack\lib\NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
```

**Comment by hebus** [comment]
Hello,

You can solve this issue with node v17 with this command line:
```bash
set NODE_OPTIONS=--openssl-legacy-provider && ng serve vanilla-search -- --ssl=true --proxyConfig=./projects/vanilla-search/src/proxy.conf.json
```
instead of the previous you use.
